# Generated by Django 6.0.4 on 2026-04-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentmethod_idempotency_key_paymentmethod_trace_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
