# Generated by Django 6.0.4 on 2026-04-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentmethod_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='brand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='expiry_month',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='expiry_year',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
