# Generated by Django 6.0.4 on 2026-05-09 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kyc_level',
            field=models.CharField(choices=[('none', 'None'), ('basic', 'Basic'), ('enhanced', 'Enhanced')], default='none', max_length=20),
        ),
        migrations.CreateModel(
            name='BasicKYCSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=255)),
                ('source_of_funds', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_kyc', to='profiles.profile')),
            ],
        ),
    ]
