# Generated by Django 6.0.4 on 2026-04-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(help_text='e.g. NG, CM', max_length=5, unique=True, verbose_name='Country Code')),
                ('slug', models.SlugField(blank=True, help_text='Used in URLs and subdomains, e.g. cm, ng', max_length=10, unique=True, verbose_name='Slug')),
                ('currency_code', models.CharField(help_text='e.g. NGN, XAF', max_length=10, verbose_name='Currency Code')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, help_text='Rate relative to the base currency (e.g. 1 USD = X XAF)', max_digits=12, verbose_name='Exchange Rate')),
                ('default_language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=5, verbose_name='Default Language')),
                ('is_default', models.BooleanField(default=False, help_text='Only one country should be set as default', verbose_name='Is Default')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
    ]
