# Generated by Django 6.0.4 on 2026-04-26 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=64, verbose_name='Fingerprint')),
                ('device_type', models.CharField(max_length=20, verbose_name='Device Type')),
                ('browser', models.CharField(max_length=100, verbose_name='Browser')),
                ('os', models.CharField(max_length=100, verbose_name='OS')),
                ('device_family', models.CharField(max_length=100, verbose_name='Device Family')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Last Seen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(blank=True, help_text='Null if the user is unauthenticated.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Device',
                'verbose_name_plural': 'User Devices',
                'unique_together': {('user', 'fingerprint')},
            },
        ),
    ]
