# Generated by Django 6.0.4 on 2026-04-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('code', models.CharField(max_length=6, verbose_name='OTP code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_verified', models.BooleanField(default=False, verbose_name='is verified')),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'ordering': ['-created_at'],
            },
        ),
    ]
