# Generated by Django 6.0.4 on 2026-04-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinstallment',
            name='transaction_id',
        ),
    ]
