# Generated by Django 6.0.4 on 2026-04-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_paymentinstallment_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_plan',
            field=models.CharField(choices=[('FP', 'Full Payment'), ('4W', '4 Weeks (weekly)'), ('2M', '2 Months (monthly)'), ('4M', '4 Months (monthly)'), ('6M', '6 Months (monthly)'), ('12M', '12 Months (monthly)')], max_length=3, verbose_name='Payment Plan'),
        ),
    ]
